apiVersion: apps/v1
kind: Deployment
metadata:
  name: aos-depl
spec:
  selector: 
    matchLabels:
      app: accountowner
  replicas: 1
  template:
    metadata:
      labels:
        app: accountowner
    spec:
      containers:
        - name: accountowner
          image: hugorodriguez/accountowner:runtime
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: accountowner-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
      name: http
  selector:
    app: accountowner
